"""initial schema (znuny_instance, tenant)

Revision ID: 755741773a47
Revises:
Create Date: 2026-05-17 01:54:59.655205

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "znuny_instance",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("db_dsn_secret_ref", sa.String(), nullable=False),
        sa.Column("webservice_token_secret_ref", sa.String(), nullable=False),
        sa.Column("webhook_signing_secret_ref", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_znuny_instance")),
        schema="gerti",
    )
    op.create_table(
        "tenant",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("legal_name", sa.String(), nullable=False),
        sa.Column("trade_name", sa.String(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("znuny_customer_id", sa.String(), nullable=False),
        sa.Column("znuny_instance_id", sa.UUID(), nullable=False),
        sa.Column("subdomain", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["znuny_instance_id"],
            ["gerti.znuny_instance.id"],
            name=op.f("fk_tenant_znuny_instance_id_znuny_instance"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("subdomain", name="uq_tenant_subdomain"),
        sa.UniqueConstraint("znuny_customer_id", name="uq_tenant_znuny_customer_id"),
        schema="gerti",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenant", schema="gerti")
    op.drop_table("znuny_instance", schema="gerti")
    # ### end Alembic commands ###
